---
auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096
  http_server_read_timeout: 300s
  http_server_write_timeout: 300s
  log_request_at_info_level_enabled: false
  log_level: warn

common:
  path_prefix: /loki
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory
    replication_factor: 1

  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules

schema_config:
  configs:
    - from: 2023-10-20
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    heartbeat_timeout: 5m

  chunk_idle_period: 2m
  chunk_retain_period: 1m
  max_chunk_age: 15m
  chunk_encoding: snappy
  chunk_target_size: 1572864
  wal:
    enabled: true
    dir: /loki/wal
    checkpoint_duration: 5m
    flush_on_shutdown: true
    replay_memory_ceiling: 1GB

limits_config:
  volume_enabled: true
  retention_period: 168h
  max_streams_per_user: 20000
  max_global_streams_per_user: 20000
  max_query_series: 15000
  max_query_length: 360h
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  ingestion_rate_mb: 25
  ingestion_burst_size_mb: 50
  split_queries_by_interval: 24h

compactor:
  working_directory: /loki/compactor
  compaction_interval: 10m
  retention_enabled: true
  retention_delete_delay: 2h
  retention_delete_worker_count: 150
  delete_request_store: filesystem

querier:
  max_concurrent: 20

query_scheduler:
  max_outstanding_requests_per_tenant: 2048

query_range:
  align_queries_with_step: true
  results_cache:
    cache:
      redis:
        endpoint: redis-local:6379
        timeout: 100ms
        db: 10
        expiration: 24h

chunk_store_config:
  chunk_cache_config:
    redis:
      endpoint: redis-local:6379
      timeout: 100ms
      db: 11
      expiration: 1h

storage_config:
  index_cache_validity: 5m
  index_queries_cache_config:
    redis:
      endpoint: redis-local:6379
      timeout: 100ms
      db: 12
      expiration: 5m

ruler:
  enable_alertmanager_discovery: false
  rule_path: /loki/rules-temp

analytics:
  reporting_enabled: false